openapi: 3.0.3

info:
  title: REWINDER
  version: '0.1'

components:
  schemas:
    IP:
      type: string

    Port:
      type: integer

    Codec:
      type: string

    Address:
      type: object
      properties:
        ip:
          $ref: '#/components/schemas/IP'
        port:
          $ref: '#/components/schemas/Port'
      required:
        - ip
        - port

    Stream:
      type: object
      properties:
        name:
          type: string
    Session:
      type: object
      properties:
        stream:
          $ref: '#/components/schemas/Stream'
        sdp:
          type: string
    Source:
      type: object
      properties:
        codec:
          $ref: '#/components/schemas/Codec'
        name:
          type: string

paths:
  /streams:
    get:
      responses:
        200:
          description: returns the available streams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stream'
  /play:
    post:
      responses:
        200:
          description: returns a matching stream, with its own sdp
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stream'
  /source:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Source'
      responses:
        200:
          description: return a UDP address for the udp stream
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
    delete:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
      responses:
        200:
          description: successfully  removed stream
