openapi: 3.0.3

info:
  title: REWINDER
  version: '0.1'

components:
  schemas:
    IP:
      type: string

    Port:
      type: number

    Codec:
      type: string

    Address:
      type: object
      properties:
        ip:
          $ref: '#/components/schemas/IP'
        port:
          $ref: '#/components/schemas/Port'
      required:
        - ip
        - port

    Stream:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/Address'
        name:
          type: string

    Source:
      type: object
      properties:
        codec:
          $ref: '#/components/schemas/Codec'
        name:
          type: string

paths:
  /streams:
    get:
      responses:
        200:
          description: returns the available streams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stream'

  /source:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Code'
      responses:
        200:
          description: return an address for
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Code'
